project_id = "vhaursnvaadhxxwefxez"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.demo-cleanup]
    verify_jwt = false
  [functions.demo-extract]
    verify_jwt = false
  [functions.extract-document]
    verify_jwt = false
  [functions.inbound-email]
    verify_jwt = false
  [functions.admin-create-user]
    verify_jwt = false
  [functions.admin-manage-user]
    verify_jwt = false
  [functions.admin-broadcast]
    verify_jwt = false
  [functions.admin-revenue-stats]
    verify_jwt = false
  [functions.admin-storage-stats]
    verify_jwt = false
  [functions.admin-login-activity]
    verify_jwt = false
  [functions.admin-gdpr]
    verify_jwt = false
  [functions.admin-login-activity]
    verify_jwt = false
  [functions.admin-system-health]
    verify_jwt = false
  [functions.setup-intent]
    verify_jwt = false
  [functions.activate-trial]
    verify_jwt = false
  [functions.billing-details]
    verify_jwt = false
  [functions.send-marketing-email]
    verify_jwt = false
