// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-expenses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-expenses.ts
var list_expenses_default = defineTool({
  name: "list_expenses",
  title: "List expenses",
  description: "List the signed-in user's expense records (supplier, amounts, VAT, category, dates), newest first. Supports optional date range, category and supplier filters.",
  inputSchema: {
    from: z.string().optional().describe("Only include invoices on/after this date (YYYY-MM-DD)."),
    to: z.string().optional().describe("Only include invoices on/before this date (YYYY-MM-DD)."),
    category: z.string().optional().describe("Filter by expense category name (exact match)."),
    supplier: z.string().optional().describe("Filter by supplier name (partial, case-insensitive)."),
    limit: z.number().int().min(1).max(200).optional().describe("Max records to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, category, supplier, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("expense_records").select(
      "id, supplier_name, invoice_number, invoice_date, due_date, category, currency, net_amount, vat_amount, total_amount"
    ).order("invoice_date", { ascending: false }).limit(limit ?? 50);
    if (from) query = query.gte("invoice_date", from);
    if (to) query = query.lte("invoice_date", to);
    if (category) query = query.eq("category", category);
    if (supplier) query = query.ilike("supplier_name", `%${supplier}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, expenses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-income.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_income_default = defineTool2({
  name: "list_income",
  title: "List income",
  description: "List the signed-in user's income records / sales invoices (customer, amounts, VAT, dates), newest first. Supports optional date range and customer filters.",
  inputSchema: {
    from: z2.string().optional().describe("Only include invoices on/after this date (YYYY-MM-DD)."),
    to: z2.string().optional().describe("Only include invoices on/before this date (YYYY-MM-DD)."),
    customer: z2.string().optional().describe("Filter by customer name (partial, case-insensitive)."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max records to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, customer, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("income_records").select(
      "id, customer_name, invoice_number, invoice_date, due_date, category, currency, net_amount, vat_amount, total_amount"
    ).order("invoice_date", { ascending: false }).limit(limit ?? 50);
    if (from) query = query.gte("invoice_date", from);
    if (to) query = query.lte("invoice_date", to);
    if (customer) query = query.ilike("customer_name", `%${customer}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, income: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-documents.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_documents_default = defineTool3({
  name: "list_documents",
  title: "List documents",
  description: "List the signed-in user's uploaded documents with their processing status, extracted fields and confidence score, newest first.",
  inputSchema: {
    status: z3.string().optional().describe("Filter by status, e.g. processing, processed, needs_review, failed."),
    document_type: z3.string().optional().describe("Filter by document type, e.g. expense_invoice or sales_invoice."),
    search: z3.string().optional().describe("Filter by file name (partial, case-insensitive)."),
    limit: z3.number().int().min(1).max(200).optional().describe("Max records to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, document_type, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("documents").select(
      "id, file_name, file_type, status, source, document_type, supplier_name, customer_name, invoice_number, invoice_date, currency, net_amount, vat_amount, total_amount, category, confidence_score, created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    if (document_type) query = query.eq("document_type", document_type);
    if (search) query = query.ilike("file_name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, documents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_categories_default = defineTool4({
  name: "list_expense_categories",
  title: "List expense categories",
  description: "List the expense categories available in the signed-in user's workspace, with colors and monthly budgets.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("expense_categories").select("id, name, color, monthly_budget").order("name", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
function totals(rows) {
  const byCurrency = {};
  for (const r of rows) {
    const cur = r.currency || "EUR";
    byCurrency[cur] ??= { total: 0, vat: 0, net: 0, count: 0 };
    byCurrency[cur].total += Number(r.total_amount ?? 0);
    byCurrency[cur].vat += Number(r.vat_amount ?? 0);
    byCurrency[cur].net += Number(r.net_amount ?? 0);
    byCurrency[cur].count += 1;
  }
  return byCurrency;
}
var financial_summary_default = defineTool5({
  name: "financial_summary",
  title: "Financial summary",
  description: "Summarise the signed-in user's income and expenses for an optional date range: totals and VAT per currency, plus expense totals per category.",
  inputSchema: {
    from: z4.string().optional().describe("Start of the period (YYYY-MM-DD, inclusive)."),
    to: z4.string().optional().describe("End of the period (YYYY-MM-DD, inclusive).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let expenseQuery = supabase.from("expense_records").select("currency, total_amount, vat_amount, net_amount, category").limit(2e3);
    let incomeQuery = supabase.from("income_records").select("currency, total_amount, vat_amount, net_amount").limit(2e3);
    if (from) {
      expenseQuery = expenseQuery.gte("invoice_date", from);
      incomeQuery = incomeQuery.gte("invoice_date", from);
    }
    if (to) {
      expenseQuery = expenseQuery.lte("invoice_date", to);
      incomeQuery = incomeQuery.lte("invoice_date", to);
    }
    const [expenseRes, incomeRes] = await Promise.all([expenseQuery, incomeQuery]);
    if (expenseRes.error) return { content: [{ type: "text", text: expenseRes.error.message }], isError: true };
    if (incomeRes.error) return { content: [{ type: "text", text: incomeRes.error.message }], isError: true };
    const expenses = expenseRes.data ?? [];
    const income = incomeRes.data ?? [];
    const byCategory = {};
    for (const e of expenses) {
      const cat = e.category || "Uncategorized";
      const cur = e.currency || "EUR";
      byCategory[cat] ??= {};
      byCategory[cat][cur] = (byCategory[cat][cur] ?? 0) + Number(e.total_amount ?? 0);
    }
    const summary = {
      period: { from: from ?? null, to: to ?? null },
      expenses: { count: expenses.length, byCurrency: totals(expenses), byCategory },
      income: { count: income.length, byCurrency: totals(income) }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vhaursnvaadhxxwefxez";
var mcp_default = defineMcp({
  name: "charmy-ai",
  title: "Charmy AI",
  version: "0.1.0",
  instructions: "Tools for Charmy AI, an accounting document platform. Read the signed-in user's expenses, income, uploaded documents and expense categories, and get period summaries of totals and VAT per currency. All data is scoped to the signed-in user's workspace.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_expenses_default,
    list_income_default,
    list_documents_default,
    list_categories_default,
    financial_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
